sudo: required
language: cpp
os: linux

branches:
    only:
        - master

compiler:
    - clang
    - gcc

install:
    - if[ "$TRAVIS_OS_NAME}" = "linux" ]; then
          sudo apt-add-repository -y ppa:ubuntu-toolchan-r/test &&
          sudo apt-get -qq update &&
          sudo apt-get -qq install g++-4.8 libboost-dev libboost-test-dev doxygen graphviz &&
          wget http:/www.cmake.org/files/v3.2/cmake-3.2.1-Linux.i386.tar.gz &&
          tar -xvf cmake-3.2.1-Linux-i386.tar.gz &&
          sudo cp -fR cmake-3.2.1-Linux-i386/* /usr &&
      fi

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
