sudo: required
language: cpp
os: linux

branches:
    only:
        - master

compiler:
    - clang
    - gcc

install:
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
           sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        && sudo apt-get -qq update
        && sudo apt-get -qq install g++-4.8 libboost-dev libboost-test-dev doxygen graphviz
        ;
      fi

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
