sudo: required
language: cpp
os: linux

compiler:
    - clang
    - gcc

install:
    - sudo add-apt-repository --yes ppa:smspillaz/cmake-master;
      sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test;
      sudo apt-get update -qq;
      sudo apt-get install cmake;
      sudo apt-get install gcc;
      sudo apt-get install libboost-dev libboost-test-dev;
      sudo apt-get install doxygen graphviz;

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
