sudo: false
language: cpp
os: linux
branches:
  only:
    - master
    - develop
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-dev
      - libboost-test-dev
      - g++-4.8
      - clang
install:
  - [ "$CXX" = "g++" ] && export CSS="g++-4.8"
script:
  - mkdir build
  - cd build
  - cmake -DVMATH_BUILD_DOC=OFF ..
  - make all check
