sudo: false
language: cpp
os: linux
branches:
  only:
    - master
    - develop
compiler:
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-dev
      - libboost-test-dev
      - clang
script:
  - make
  - cd build
  - make 
  - make check
