sudo: false
language: cpp
os: linux

branches:
    only:
        - master
        - develop

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - libboost-dev
            - libboost-test-dev

compiler:
    - clang
    - gcc

script:
    - mkdir build
    - cd build
    - cmake -DVMATH_BUILD_DOC=OFF ..
    - make
    - make test
