sudo: false
language: cpp
os: linux
branches:
  only:
    - master
    - develop
compiler:
  - clang
  - g++
addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
      - libboost-dev
      - libboost-test-dev
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++"]; then export CXX="clang++-3.7" CC="clang-2.7"; fi
script:
  - make
  - cd build
  - make 
  - make check
