sudo: false
language: cpp
os: linux
branches:
  only:
    - master
    - develop
compiler:
  - clang
addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
      - kalakris-cmake
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
      - cmake
      - libboost-dev
      - libboost-test-dev
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
script:
  - $CXX --version
  - cmake --version
  - make
  - cd build
  - make 
  - make check
