sudo: required
language: cpp
os: linux

branches:
    only:
        - master

compiler:
    - clang
    - gcc

install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get -qq install g++-4.8 libboost-dev libboost-test-dev doxygen graphviz
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq c++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
